name: Verify

on:
  workflow_dispatch:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

permissions:
  contents: read

jobs:
  verify:
    name: verify
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src
      - uses: lukka/get-cmake@latest
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - run: bash scripts/verify
        shell: bash
